In [ ]:
#Import Packages
import pandas as pd
import os
import numpy as np
from bs4 import BeautifulSoup
import lxml
import json
import matplotlib.pyplot as plt
from google.colab import drive
import warnings

#Packages for images and ML models
from sklearn.model_selection import train_test_split
import cv2, glob, pathlib
from PIL import Image, ImageDraw


warnings.filterwarnings('ignore')
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [ ]:
normal_path = "drive/MyDrive/VijayV_Persuasion_Strategies_Project/train_images" #You will need to replace this with your own link to you local drive
list_normal = os.listdir(normal_path) #list of all normal images

In [ ]:
#Create pandas dataframe
number = 1
number_2 = 0

class_labels_normal = []

for room in list_normal:
  class_labels_normal.append(number_2)
print (class_labels_normal)

d = {'images':list_normal,'label':class_labels_normal}
normalpd = pd.DataFrame(d)
normalpd.head(2000)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

images  label
0      21443.jpg      0
1     158884.jpg      0
2     125287.jpg      0
3     120716.jpg      0
4      45742.jpg      0
...          ...    ...
1987  133746.jpg      0
1988  158591.jpg      0
1989  161173.jpg      0
1990   36271.jpg      0
1991  149942.jpg      0

[1992 rows x 2 columns]

In [ ]:
len(list_normal)

1992

In [ ]:
list_images_normal = []
list_normal_labels = []

for image in list_normal:
  image = cv2.imread(str(normal_path + "/" + image))
  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
  image = cv2.resize(image, (180, 180))

  list_images_normal.append(image)
  list_normal_labels.append(0)
  break


list_total = list_images_normal
list_total_labels = list_normal_labels


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [ ]:
X_array = np.array(list_total)
y_array = np.array(list_total_labels)

In [ ]:
# X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, test_size=0.2)
# X_train = X_train.astype("float32")
# X_test = X_test.astype("float32")

ValueError: ignored

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import models, layers

In [ ]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

class line:
    def __init__(self, p1, p2):
        self.p1 = p1
        self.p2 = p2

def onLine(l1, p):
    # Check whether p is on the line or not
    if (
        p.x <= max(l1.p1.x, l1.p2.x)
        and p.x <= min(l1.p1.x, l1.p2.x)
        and (p.y <= max(l1.p1.y, l1.p2.y) and p.y <= min(l1.p1.y, l1.p2.y))
    ):
        return True
    return False

def direction(a, b, c):
    val = (b.y - a.y) * (c.x - b.x) - (b.x - a.x) * (c.y - b.y)
    if val == 0:
        # Collinear
        return 0
    elif val < 0:
        # Anti-clockwise direction
        return 2
    # Clockwise direction
    return 1

def isIntersect(l1, l2):
    # Four direction for two lines and points of other line
    dir1 = direction(l1.p1, l1.p2, l2.p1)
    dir2 = direction(l1.p1, l1.p2, l2.p2)
    dir3 = direction(l2.p1, l2.p2, l1.p1)
    dir4 = direction(l2.p1, l2.p2, l1.p2)

    # When intersecting
    if dir1 != dir2 and dir3 != dir4:
        return True

    # When p2 of line2 are on the line1
    if dir1 == 0 and onLine(l1, l2.p1):
        return True

    # When p1 of line2 are on the line1
    if dir2 == 0 and onLine(l1, l2.p2):
        return True

    # When p2 of line1 are on the line2
    if dir3 == 0 and onLine(l2, l1.p1):
        return True

    # When p1 of line1 are on the line2
    if dir4 == 0 and onLine(l2, l1.p2):
        return True

    return False

def checkInside(poly, p):
    n = len(poly)

    if n<3:
      return False

    # Create a point at infinity, y is same as point p
    exline = line(p, Point(10000, p.y))
    count = 0
    i = 0
    while True:
        # Forming a line from two consecutive points of poly
        side = line(poly[i], poly[(i + 1) % n])
        if isIntersect(side, exline):
            # If side is intersects ex
            if (direction(side.p1, p, side.p2) == 0):
                return onLine(side, p);
            count += 1

        i = (i + 1) % n;
        if i == 0:
            break

    # When count is odd
    return count & 1;


# Driver code
polygon = [  Point( 0, 0 ), Point( 10, 0 ), Point( 10, 10 ), Point( 0, 10 ) ];
p = Point( 3, 5 );

# Function call
if (checkInside(polygon, p)):
    print("Point is inside.")
else:
    print("Point is outside.")

Point is inside.


In [ ]:
def draw_lines_from_string(draw, pointstring):
    points = pointstring.split(";")
    xcoords = []
    ycoords = []
    for point in points:
      spl = point.split(",")
      xcoords.append(int(float(spl[0])))
      ycoords.append(int(float(spl[1])))
    for i in range(-1,len(xcoords)-1):
      draw.line((xcoords[i],ycoords[i],xcoords[i+1],ycoords[i+1]), fill=(255, 255, 255), width=3)

def point_array_from_string(pointstring):
    points = pointstring.split(";")
    point_array = []
    for point in points:
      spl = point.split(",")
      point_array.append(Point(int(float(spl[0])), int(float(spl[1]))))
    return point_array

In [ ]:
#Display (fyi)
# Image.open("drive/MyDrive/train_images_folder/train_images/"+list_normal[345]) #Parse through one single image
i = Image.open("drive/MyDrive/VijayV_Persuasion_Strategies_Project/train_images/40172.jpg")
i.show()


def display(display_list):
  plt.figure(figsize=(10, 10))

  title = ['Input Image', 'True Mask', 'Predicted Mask']

  for i in range(len(display_list)):
    plt.subplot(1, len(display_list), i+1)
    plt.title(title[i])
    plt.imshow(tf.keras.utils.array_to_img(display_list[i]))
    plt.axis('off')
  plt.show()


In [ ]:
with open('drive/MyDrive/VijayV_Persuasion_Strategies_Project/segmentation.xml', 'r') as f:
    data = f.read()
Bs_data = BeautifulSoup(data, "xml")
images_xml = Bs_data.find_all('image')
# for i in range(len(images_xml)):
for i in range(3):
    image_x = images_xml[i]
    polygons = image_x.find_all('polygon')
    boxes = image_x.find_all('box')
    shapestrings = []
    for polygon in polygons:
        shapestrings.append(polygon.get("points"))
    # for box in boxes:
    #     xtl = box.get("xtl")
    #     ytl = box.get("ytl")
    #     xbr = box.get("xbr")
    #     ybr = box.get("ybr")
    #     boxstring = f"{xtl},{ytl};{xbr},{ytl};{xbr},{ybr};{xtl},{ybr}"
    #     shapestrings.append(boxstring)
    try:
      j = Image.open("drive/MyDrive/VijayV_Persuasion_Strategies_Project/train_images/"+image_x.get("name"))
      print(j.size)
    except:
      pass
    draw = ImageDraw.Draw(j)
    for coords in shapestrings:
      draw_lines_from_string(draw,coords)
    j.show()
    polygonshape = point_array_from_string(shapestrings[0])
    tftensor = []
    for a in range(j.size[1]):
      tfrow = []
      for b in range(j.size[0]):
        if(checkInside(polygonshape, Point(b,a))):
          tfrow.append([1])
        else:
          tfrow.append([0])
      tftensor.append(tfrow)
    tensor_from_list = tf.constant(tftensor)
    print(tensor_from_list.shape)
    display([tensor_from_list])

# Deciding the model structure

**Including Text**

If we look through the persuasion strategies at [this part of the website](https://midas-research.github.io/persuasion-advertisements/CategoryWisePage.html), then it becomes clear that text is extremely important in classifying the persuasion strategies, more important than even the images.

Fortunately, the creators of the dataset provide the text that is in all the advertisements, so we can use that along with the image to classify persuasion strategies, but we need to create a multi-modal classifier, which will be difficult.

However, I found some tutorials online and I think that it is possible to implement for us. I will read a lot about multi-modal classifiers and will figure out how to implement it. We can even test different versions and compare the accuracy.

Multi-modal classifier tutorials:
*   https://github.com/dsaidgovsg/multimodal-learning-hands-on-tutorial/tree/main
*   https://vaclavkosar.com/ml/Multimodal-Image-Text-Classification
*   https://drivendata.co/blog/hateful-memes-benchmark/






**Deciding Image structure**

We also need to figure out what types of images we will input into the model.
Methods that I think we can try:
*   Using the U-NET model to find objects in the image and then only using those objects.
*   Using the whole image + extra emphasis on the objects in the image detected by U-NET

Another important thing is that they only gave image segmentation masks for 250 images, so we might have to create our own image segmentations masks if that is not enough images to train the U-NET model. If so, we need to figure out an efficient way to draw our own masks quickly, which I can do by next week.


# Creating the dataset

Some strategies I think we should exclude are:
Anthropomorphism
Unclear



In [ ]:
imagedetectablestrats = ["Active", "Amazed", "Eager", "Fashionable", "Feminine","Cheerful"]

trainimages = {}
testimages = {}

f = open('drive/MyDrive/VijayV_Persuasion_Strategies_Project/annotations_file_train_set.json', 'r')
train_data = json.load(f)
f = open('drive/MyDrive/VijayV_Persuasion_Strategies_Project/annotations_test_set.json', 'r')
test_data = json.load(f)

for i in train_data:
    strategies = []
    strategies.append(train_data[i]['First Persuasion'].split(" ")[0])
    strategies.append(train_data[i]['Second Persuasion'].split(" ")[0])
    strategies.append(train_data[i]['Third Persuasion'].split(" ")[0])
    strats = []
    for strat in strategies:
      if strat in imagedetectablestrats:
        strats.append(strat)
    if len(strats)>0:
      trainimages.update({i.split("/")[1]:strats})
for i in test_data:
    strategies = []
    strategies.append(test_data[i]['First Persuasion'].split(" ")[0])
    strategies.append(test_data[i]['Second Persuasion'].split(" ")[0])
    strategies.append(test_data[i]['Third Persuasion'].split(" ")[0])
    strats = []
    for strat in strategies:
      if strat in imagedetectablestrats:
        strats.append(strat)
    if len(strats)>0:
      testimages.update({i.split("/")[1]:strats})
print(len(trainimages))
print(len(testimages))

1468
149


In [ ]:
allimages = dict.copy(trainimages)
allimages.update(testimages)

count = 0
for entry, val in allimages.items():
    count+=1
    print(str(count) + ": ", end="")
    print(entry)
    print(val)
    print()

1: 3947.jpg
['Cheerful']

2: 6873.jpg
['Eager']

3: 6922.jpg
['Active']

4: 9095.jpg
['Fashionable']

5: 9567.jpg
['Fashionable']

6: 10438.jpg
['Eager']

7: 11059.jpg
['Eager']

8: 15033.jpg
['Active']

9: 17463.jpg
['Eager']

10: 18862.jpg
['Active']

11: 23239.jpg
['Feminine']

12: 23657.jpg
['Fashionable']

13: 24592.jpg
['Fashionable']

14: 27178.jpg
['Eager']

15: 31516.jpg
['Fashionable']

16: 31894.jpg
['Fashionable']

17: 32717.jpg
['Eager']

18: 33141.jpg
['Feminine']

19: 38327.jpg
['Eager']

20: 38620.jpg
['Active']

21: 39439.jpg
['Fashionable']

22: 40936.jpg
['Fashionable']

23: 48535.jpg
['Cheerful']

24: 49780.jpg
['Active']

25: 50130.jpg
['Cheerful']

26: 50853.jpg
['Feminine']

27: 51274.jpg
['Feminine']

28: 53222.jpg
['Active']

29: 58636.jpg
['Eager']

30: 59409.jpg
['Fashionable']

31: 61078.jpg
['Amazed']

32: 64310.jpg
['Fashionable']

33: 65523.jpg
['Eager']

34: 65878.jpg
['Feminine']

35: 69869.jpg
['Amazed']

36: 72516.jpg
['Amazed']

37: 75326.jpg
['Femin

In [ ]:
import shutil

# specify your source path and destination path here
src = '/content/drive/MyDrive/VijayV_Persuasion_Strategies_Project/train_images/'
dst = '/content/drive/MyDrive/VijayV_Persuasion_Strategies_Project/images_to_annotate'

# use shutil to copy the file
imagedetectablestrats1 = imagedetectablestrats[0:4]


In [ ]:
print(imagedetectablestrats[4:])

['Active', 'Amazed', 'Eager', 'Fashionable']


In [ ]:
for strat in imagedetectablestrats1:
    stratcount = 0
    for image in trainimages.keys():
        if(trainimages[image]==strat and stratcount<100):
          stratcount+=1
          try:
            shutil.copy(src+image, dst)
          except:
            stratcount-=1
    print(strat, stratcount)

Active 100
Amazed 69
Eager 100
Fashionable 100


In [ ]:
imagedetectablestrats2 = ["Feminine","Cheerful"]
dst = '/content/drive/MyDrive/VijayV_Persuasion_Strategies_Project/images_to_annotate2'
for strat in imagedetectablestrats2:
    stratcount = 0
    for image in trainimages.keys():
        if(trainimages[image]==strat and stratcount<100):
          stratcount+=1
          try:
            shutil.copy(src+image, dst)
          except:
            stratcount-=1
    print(strat, stratcount)

Feminine 95
Cheerful 100


In [ ]:
trainimages['172836.png']

'Active'